name: Build koolcenter Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 1dfda1410a17ad1e469e1283f0ba150fc68a2612
        fetch-depth: 1
        
    - name: Remove .git to prevent submodule issues
      run: rm -rf .git
      
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          automake autoconf libtool \
          bison flex git wget unzip \
          libssl-dev zlib1g-dev \
          python2
        
    - name: Fix Python 2 scripts
      run: |
        cd koolcenter
        sed -i '1s|^.*$|#!/usr/bin/env python2|' gen_install.py
        sed -i 's|print \(.*\)|print(\1)|g' gen_install.py
        chmod +x gen_install.py
        touch to_remove.txt
        chmod +x build_hnd.sh
      
    - name: Bypass platform check and fix find command
      run: |
        cd koolcenter
        
        # 修复平台检测
        echo "修改 softcenter/install.sh 绕过平台检测..."
        sed -i '/platform_test()/{:a;N;/^}$/!ba; s/.*/platform_test(){\n\techo_date "⚠️ 已跳过平台检测，强制安装！"\n}/}' softcenter/install.sh
        
        # 修复 find 命令兼容性问题
        echo "修复 find 命令兼容性..."
        sed -i 's/find -L \/koolshare\/ -type l | xargs rm -rf/# 修复BusyBox兼容性问题\nfor link in $(ls -l /koolshare/ | grep "^l" | awk "{print \\\$9}"); do\n    if [ ! -e "/koolshare/\\\$link" ]; then\n        rm -rf "/koolshare/\\\$link"\n    fi\ndone/' softcenter/install.sh
        
        # 验证修改
        echo "修改后的 platform_test 函数:"
        grep -A 2 "platform_test()" softcenter/install.sh
        echo "修改后的 find 命令:"
        grep -A 5 "修复BusyBox兼容性问题" softcenter/install.sh
      
    - name: Execute build script
      run: |
        cd koolcenter
        ./build_hnd.sh
        
    - name: Archive package
      run: |
        cd koolcenter
        PKG=$(find . -name "*.tar.gz" -print -quit)
        if [ -n "$PKG" ]; then
          mv "$PKG" koolcenter_build.tar.gz
          echo "Package size: $(du -h koolcenter_build.tar.gz)"
        else
          echo "::error::No package file found!"
          find . -type f
          exit 1
        fi
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: koolcenter-package
        path: koolcenter/koolcenter_build.tar.gz
