name: Build koolcenter Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 1dfda1410a17ad1e469e1283f0ba150fc68a2612
        fetch-depth: 1  # 浅层克隆
        
    - name: Remove .git to prevent submodule issues
      run: rm -rf .git  # 彻底移除git相关文件
      
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          automake autoconf libtool \
          bison flex git wget unzip \
          libssl-dev zlib1g-dev
        
    - name: Prepare build directory
      run: |
        cd koolcenter
        chmod +x build_hnd.sh
      
    - name: Execute build script
      run: |
        cd koolcenter
        ./build_hnd.sh
        
    - name: Archive package
      run: |
        cd koolcenter
        mv $(find . -name "*.tar.gz" -print -quit) koolcenter_build.tar.gz
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: koolcenter-package
        path: koolcenter/koolcenter_build.tar.gz
